redis:
  image: redis:latest
  command: redis-server --appendonly yes

web:
  image: sentry:onbuild
  links:
    - redis:redis
  ports:
    - 9000:9000
  env_file: .env

cron:
  image: sentry:onbuild
  links:
    - redis:redis
  env_file: .env
  command: sentry run cron

worker:
  image: sentry:onbuild
  links:
    - redis:redis
  env_file: .env
  command: sentry run worker

